name: Release

on:
  push:
    tags:
      - 'v*'

# Явно даём права на запись в репозиторий (нужно для создания релизов)
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install NASM
      run: sudo apt-get update && sudo apt-get install -y nasm
    
    - name: Build
      run: |
        nasm -f elf64 xor.asm -o xor.o
        ld -o tiny-xor xor.o
    
    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        files: tiny-xor
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
